# -*- coding: utf-8 -*-
"""Experta_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GC7d1RvUzsRslubwE3b8j8s2Z2EdISCS
"""

!pip install experta

!pip install --upgrade frozendict

from experta import *

class SistemPakarMedis(KnowledgeEngine):

  @Rule(Fact(demam=True) & Fact(batuk=True))
  def Flu(self):
    print("Diagnosis: Flu.")

  @Rule(Fact(sakit_tenggorokan=True) & Fact(demam=True))
  def Radang_Tenggorokan(self):
    print("Diagnosis: Radang Tenggorokan.")

  @Rule(Fact(nyeri_otot=True) & Fact(nyeri_perut=True))
  def Hernia(self):
    print("Diagnosis: Hernia.")

  @Rule(Fact(kanker=True) & Fact(tbc=True) & Fact(tipes=True) & Fact(tumor=True))
  def Kanker(self):
    print("Diagnosis: Krisis.")

  @Rule(Fact(Batuk_berdahak=True) & Fact(suara_mengi=True) & Fact(sesak_nafas=True) & Fact(mudah_lemas=True) )
  def Asma(self):
    print("Diagnosis: Asma.")

  @Rule(Fact(nyeri_perut=True) & Fact(mual=True) & Fact(sakit_kepala=True) & Fact(mudah_lemas=True))
  def Types(self):
    print("Diagnosis: Types.")

  @Rule(Fact(Gatal=True) & Fact(Bersin=True) & Fact(Ruam=True) & Fact(mual=True))
  def Alergi(self):
    print("Diagnosis: Alergi.")

  @Rule(Fact(nyeri_kepala=True) & Fact(demam_tinggi=True) & Fact(mual=True) & Fact(Ruam=True))
  def Demam_Berdarah(self):
    print("Diagnosis: Demam Berdarah.")

  @Rule(Fact(Sesak=True) & Fact(Batuk=True) & Fact(Suara_mengi=True) & Fact(nyeri_dada=True))
  def Bronkitis(self):
    print("Diagnosis: Bronkitis.")

  @Rule(Fact(delusi=True) & Fact(susah_fokus=True) & Fact(no_emosi=True) & Fact(halusinasi=True) & Fact(perilaku_aneh=True) )
  def Skizofrenia(self):
    print("Diagnosis: Skizofrenia.")

#Running the expert system
engine = SistemPakarMedis()
engine.reset()
engine.declare(Fact(Sesak=True))
engine.declare(Fact(Batuk=True))
engine.declare(Fact(Suara_mengi=True))
engine.declare(Fact(nyeri_dada=True)) # input symptoms
engine.run()