# -*- coding: utf-8 -*-
"""Experta_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xULan8KTuFN4b29sk1077o6TFRnJDxFL
"""

!pip install experta

!pip install --upgrade frozendict

from experta import *

class Diagnosis(KnowledgeEngine):

  @Rule(Fact (cough=True) & Fact(fever=True) & Fact (fatigue=True))
  def flu(self):
    print("Diagnosis: You may have the flu.")

  @Rule(Fact (cough=True) & Fact(fever=True) & Fact (breathing_difficulty=True))
  def pneumonia(self):
    print("Diagnosis: You may have the pneumonia.")

  @Rule(Fact(sneezing=True) & Fact(runny_nose=True) & Fact (cough=False))
  def cold(self):
    print("Diagnosis: You may have a common Cold.")

  @Rule(Fact(sore_throat=True) & Fact(fever=True))
  def throt_infection(self):
    print("Diagnosis: You may have a Throat Infection.")

  @Rule(Fact(productive_cough=True) & Fact(wheezing=True) & Fact(shortness_of_breath=True) & Fact(easily_fatigued=True))
  def Asthma(self):
    print("Diagnosis: You may have the Asthma.")

  @Rule(Fact(stomach_pain=True) & Fact(nausea=True) & Fact(headache=True) & Fact(easily_fatigued=True))
  def Typhoid(self):
    print("Diagnosis: You may have a Typhoid (Tipes).")

  @Rule(Fact(itchiness=True) & Fact(sneezing=True) & Fact(rash=True) & Fact(nausea=True))
  def Allergy(self):
    print("Diagnosis: You may have a Allergy.")

  @Rule(Fact(headache=True) & Fact(high_fever=True) & Fact(nausea=True) & Fact(rash=True))
  def Dengue_Fever(self):
    print("Diagnosis: You may have the Dengue Fever.")

  @Rule(Fact(shortness_of_breath=True) & Fact(cough=True) & Fact(wheezing=True) & Fact(chest_pain=True))
  def Bronchitis(self):
    print("Diagnosis: You may have the Bronchitis.")

  @Rule(Fact(cough=False) & Fact(fever=False) & Fact (fatigue=False))
  def Healthy(self):
    print("Diagnosis: You seem to be healthy.")

def get_input():
  """Helper function to get user input as boolean (yes/no)."""
  def ask_question(question):
    return input(question + "(yes/no): ").strip().lower() == "yes"

  return {
      "cough": ask_question("Do you have a cough?"),
      "fever": ask_question("Do you have a fever?"),
      "fetigue": ask_question("Do you feel fetiguaded?"),
      "breathing_difficulty": ask_question("Do you have breathing difficulties?"),
      "sneezing": ask_question("Are you sneezing?"),
      "runny_nose": ask_question("Do you have a runny nose?"),
      "sore_throat": ask_question("Do you have a sore throat?"),
      "wheezing": ask_question("Do you hear a wheezing sound when you breathe?"),
      "productive_cough": ask_question("Do you have a productive (phlegmy) cough?"),
      "shortness_of_breath": ask_question("Are you experiencing shortness of breath?"),
      "easily_fatigued": ask_question("Do you get tired easily with minimal activity?"),
      "stomach_pain": ask_question("Do you have stomach or abdominal pain?"),
      "headache": ask_question("Are you experiencing headaches?"),
      "fatigue_typhoid": ask_question("Do you feel tired or weak more than usual?"),
      "itchiness": ask_question("Do you feel itchy, especially on your skin or eyes?"),
      "rash": ask_question("Do you have a skin rash or red spots?"),
      "nausea": ask_question("Do you feel nauseous or have vomiting?"),
      "high_fever": ask_question("Do you have a high fever (above 39°C)?"),
      "chest_pain": ask_question("Do you feel tightness or pain in your chest?")
  }

#Running the expert system
if __name__ == "__main__":
  symptoms = get_input()
  engine = Diagnosis()
  engine.reset() # reset the knowledge engine

  for symptom, present in symptoms.items():
    engine.declare(Fact(**{symptom: present})) # declare fact

  engine.run() #run the inference engine