# -*- coding: utf-8 -*-
"""Forward_Chain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w7x49xn1lR82zSs3CbtKoqm_FMA3LBsE
"""

def forward_chaining(fact, rules):
  inferred = set(facts)
  changed = True

  while changed:
    changed = False
    for rule in rules:
      if rule["if"].issubset(inferred) and rule["then"] not in inferred:
        inferred.add(rule["then"])
        changed = True
  return inferred


facts = {"has_feathers", "has_beak", "cannot_fly"}
rules = [
    {"if": {"has_feathers", "has_beak"}, "then": "is_bird"},
    {"if": {"lays_egg", "is_bird"}, "then": "is_chicken"},
    {"if": {"cannot_fly", "is_bird"}, "then": "is_penguin"},
    {"if": {"carnivora", "is_bird"}, "then": "is_eagle"}
]

result = forward_chaining(facts, rules)
print("Inferred  facts: ", result)

def forward_chaining(facts, rules):
  inferred = set(facts)
  changed = True

  while changed:
    changed = False
    for rule in rules:
      if rule["if"].issubset(inferred) and rule["then"] not in inferred:
        inferred.add(rule["then"])
        changed = True
  return inferred
facts = {"has_wheels", "has_engine", "has_four_wheels"}
rules = [
      {"if": {"has_wheels", "has_engine"}, "then": "is_vehicle"},
      {"if": {"is_vehicle", "has_two_wheels"}, "then": "is_motorcycle"},
      {"if": {"is_vehicle", "has_four_wheels"}, "then": "is_car"},
  ]
result = forward_chaining(facts, rules)
print("Inferred facts: ", result)